### ISSUE TITLE
Review initial code

### ISSUE THREAD

**Issue by dracos** [mysociety/sort-my-sign#2]
Can't PR as it's the whole repo to be given a check over :)

**Comment by chrismytton** [comment]
@dracos Overall looks good to me! Just a few questions/suggestions below 🙂 

---

https://github.com/mysociety/sort-my-sign/blob/e25364b8bfc90311460765173f2db942c2f4cc70/perllib/FixMyStreet/Cobrand/TransportFocus.pm#L73

Perhaps worth changing this text to say "Sort My Sign is a UK based website. …" or similar?

---

https://github.com/mysociety/sort-my-sign/blob/e25364b8bfc90311460765173f2db942c2f4cc70/bin/make-jn-database#L48

Can we document where this `roads.csv` file comes from/how it can be generated?

---

https://github.com/mysociety/sort-my-sign/blob/e25364b8bfc90311460765173f2db942c2f4cc70/script/test#L4-L6

Doesn't seem like the first `cd` is necessary?

**Comment by dracos** [comment]
Thanks, all updated :) Will PR any new things from now on!
